language: python
python:
  - "3.9"
before_install:
  - cd app
install:
  - pip3 install -r requirements.txt
script:
  - sudo service postgresql restart
  - pg_lsclusters
  - python3 manage.py test polls/tests_test/unit_tests
  - python3 manage.py test polls/tests_test/integration_tests
  - python3 manage.py test polls/tests_test/e2e_tests